title:
  en: Page
  it: Pagina

pages: false

options:
  preview: true
  template: false
  status: true
  url: true
  delete: true

fields:

  seo:
    extends: seo

  hero:
    extends: hero
    fields:
      heroIcon:
        type: hidden
      heroCTATitle:
        type: hidden
      heroCTAUrl:
        type: hidden

  bodyHeadline:
    label:
      en: Body
      it: Body
    type: headline

  text:
    label:
      en: Text
      it: Testo
    type: textarea
