title:
  en: Page
  it: Pagina

pages: false

options:
  preview: true
  template: false
  status: true
  url: true
  delete: true

fields:
  seoHeadline:
    label:
      en: SEO
      it: SEO
    type: headline

  title:
    label:
      en: Title
      it: Titolo
    type: text

  description:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 160

  tags:
    label:
      en: Keywords
      it: Keywords
    type: tags
    lower: true
    index: all

  hero:
    extends: hero
    fields:
      heroIcon:
        type: hidden
      heroCTATitle:
        type: hidden
      heroCTAUrl:
        type: hidden

  bodyHeadline:
    label:
      en: Body
      it: Body
    type: headline

  text:
    label:
      en: Text
      it: Testo
    type: textarea
