title:
  en: Products
  it: Prodotti

files: false

pages:
  template: products-category

options:
  status: false
  template: false
  url: false
  delete: false

fields:

  seoHeadline:
    label:
      en: SEO
      it: SEO
    type: headline

  title:
    label:
      en: Title
      it: Titolo
    type: text

  description:
    label:
      en: Description
      it: Descrizione
    type: textarea

  tags:
    label:
      en: Keywords
      it: Keywords
    type: tags
    lower: true
    index: all

  heroHeadline:
    label:
      en: Hero
      it: Hero
    type: headline

  heroTitle:
    label:
      en: Title
      it: Titolo
    type: text

  heroText:
    label:
      en: Description
      it: Descrizione
    type: textarea
