title:
  en: Product category
  it: Categoria prodotti

files:
  type: image

pages:
  sort: flip
  template:
    - product
    - products-category

options:
  preview: true
  template: false
  status: true
  url: true
  delete: true

fields:
  seoHeadline:
    label:
      en: SEO
      it: SEO
    type: headline

  title:
    label:
      en: Title
      it: Titolo
    type: text

  description:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 160

  tags:
    label:
      en: Keywords
      it: Keywords
    type: tags
    lower: true
    index: all
  
  heroHeadline:
    label:
      en: Hero
      it: Hero
    type: headline

  hero:
    extends: hero
    fields:
      heroImage:
        type: hidden
      heroGallery:
        type: hidden
      heroCTATitle:
        type: hidden
      heroCTAUrl:
        type: hidden
