title:
  en: Products
  it: Prodotti

files: false

pages:
  template: products-category

options:
  preview: true
  status: false
  template: false
  url: true
  delete: true

fields:

  seoHeadline:
    label:
      en: SEO
      it: SEO
    type: headline

  title:
    label:
      en: Title
      it: Titolo
    type: text

  description:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 160

  tags:
    label:
      en: Keywords
      it: Keywords
    type: tags
    lower: true
    index: all

  hero:
    extends: hero
    fields:
      heroIcon:
        type: hidden
      heroCTATitle:
        type: hidden
      heroCTAUrl:
        type: hidden
