title:
  en: Product category
  it: Categoria prodotti

files:
  type: image

pages:
  template:
    - product
    - products-category

options:
  preview: true
  template: false
  status: true
  url: true
  delete: true

fields:
  seoHeadline:
    label:
      en: SEO
      it: SEO
    type: headline

  title:
    label:
      en: Title
      it: Titolo
    type: text

  description:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 160

  tags:
    label:
      en: Keywords
      it: Keywords
    type: tags
    lower: true
    index: all
  
  heroHeadline:
    label:
      en: Hero
      it: Hero
    type: headline

  heroIcon:
    label:
      en: Icon
      it: Icona
    type: image
    help:
      en: 'Recommended: size 96px by 96px and svg format'
      it: 'Consigliato: dimensione 96px per 96px e formato svg'

  heroTitle:
    label:
      en: Title
      it: Titolo
    type: text

  heroText:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 250
