title:
  en: Product category
  it: Categoria prodotti

files:
  type: image

pages:
  sort: flip
  template:
    - product
    - products-category

options:
  preview: true
  template: false
  status: true
  url: true
  delete: true

fields:

  seo:
    extends: seo

  hero:
    extends: hero
    fields:
      heroImage:
        type: hidden
      heroGallery:
        type: hidden
      heroCTATitle:
        type: hidden
      heroCTAUrl:
        type: hidden
