title:
  en: Product
  it: Prodotto

files:
  sortable: true
  type:
    - image
    - document

pages: false

options:
  template: false

fields:
  seoHeadline:
    label:
      en: SEO
      it: SEO
    type: headline

  title:
    label:
      en: Title
      it: Titolo
    type: text

  description:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 160

  tags:
    label:
      en: Keywords
      it: Keywords
    type: tags
    lower: true
    index: all

  heroHeadline:
    label:
      en: Hero
      it: Hero
    type: headline

  heroImage:
    label:
      en: Image
      it: Immagine
    type: image
    help:
      en: 'Recommended: images with ratio 1:1 (square) 1200px wide, with transparency'
      it: 'Consigliato: immagini con il rapporto 1:1 (quadrata) larga 1200px, con la trasparenza'
    required: true

  heroTitle:
    label:
      en: Title
      it: Titolo
    type: text

  heroText:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 250

  productHeadline:
    label:
      en: Media
      it: Media
    type: headline

  gallery:
    label:
      en: Gallery
      it: Galleria
    type: images
    help:
      en: 'Recommended: bigger image even 1920px wide, with transparency'
      it: 'Consigliato: immagine grande 1920px larga, con la trasparenza'

  iframe:
    label:
      en: Video iframe
      it: Video iframe
    type: url
    width: 1/2
    help:
      en: 'Link of full url of YouTube or Vimeo'
      it: 'Link dell’intero url da YouTube o Vimeo'

  document:
    label:
      en: Document
      it: Documento
    type: quickselect
    options: documents
    width: 1/2
    help:
      en: 'File extention: pdf, doc, docx, xls, xlsx, ppt, csv, rtf'
      it: 'Estensione file: pdf, doc, docx, xls, xlsx, ppt, csv, rtf'

  bodyHeadline:
    label:
      en: Body
      it: Body
    type: headline

  text:
    label:
      en: Text
      it: Testo
    type: textarea

  specsHeadline:
    label:
      en: Tech specs
      it: Specifiche tecniche
    type: headline

  specs:
    label:
      en: Table
      it: Tabella
    type: structure
    entry: >
      {{title}}
    modalsize: large
    fields:
      title:
        label:
          en: Title
          it: Titolo
        type: text
      description:
        label:
          en: Description
          it: Descrizione
        type: textarea
        buttons: false
