title:
  en: Products
  it: Prodotti

files: false

pages:
  template: products-category

options:
  preview: true
  status: false
  template: false
  url: true
  delete: true

fields:

  seoHeadline:
    label:
      en: SEO
      it: SEO
    type: headline

  title:
    label:
      en: Title
      it: Titolo
    type: text

  description:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 160

  tags:
    label:
      en: Keywords
      it: Keywords
    type: tags
    lower: true
    index: all

  heroHeadline:
    label:
      en: Hero
      it: Hero
    type: headline

  heroImage:
    label:
      en: Image
      it: Immagine
    type: image

  heroGallery:
    label:
      en: Gallery
      it: Galleria
    type: images

  heroTitle:
    label:
      en: Title
      it: Titolo
    type: text

  heroText:
    label:
      en: Description
      it: Descrizione
    type: textarea
    buttons: false
    validate:
      maxLength: 250
