title:
  en: Products
  it: Prodotti

files: false

pages:
  template: products-category

options:
  preview: true
  status: false
  template: false
  url: true
  delete: true

fields:

  seo:
    extends: seo

  hero:
    extends: hero
    fields:
      heroIcon:
        type: hidden
      heroCTATitle:
        type: hidden
      heroCTAUrl:
        type: hidden
